telegram:
  bot-token: "8373530125:AAEYBMuf2nPgvMQ5sVb0WiXpFptEiOlVQFw"
  telegram-format: "[MC] {player}: {message}"
  minecraft-format: "&6[TG] &f{username}: &7{message}"

chat:
  enabled: true
  max-message-length: 256
  command-prefix: "&8[&6TCB&8]&r"
  debug: true

server:
  name: "Minecraft Server"
  notifications:
    enabled: true
    start-message: "🟢 Server started!"
    stop-message: "🔴 Server stopped!"

